apiVersion: apps.kaxonliu.com/v1
kind: YellowTang
metadata:
  labels:
    app.kubernetes.io/name: yellowtang
    app.kubernetes.io/managed-by: kustomize
  name: yellowtang-sample
spec:
  # TODO(user): Add fields here
